apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-hierarquical-processes
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: "spark-lance-gcs:4.0.2"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/scripts/job.py"
  sparkVersion: "4.0.2"
  timeToLiveSeconds: 300
  restartPolicy:
    type: Never
  sparkConf:
    "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "spark.hadoop.google.cloud.auth.type": "APPLICATION_DEFAULT"
    "spark.sql.extensions": "org.lance.spark.extensions.LanceSparkSessionExtensions"
    "spark.sql.catalog.sandbox": "org.lance.spark.LanceNamespaceSparkCatalog"
    "spark.sql.catalog.sandbox.impl": "dir"
    "spark.sql.catalog.sandbox.root": "gs://thiagos-lake/sandbox"
  volumes:
    - name: script
      configMap:
        name: spark-hierarquical-processes-script
    - name: gcs-adc
      secret:
        secretName: gcs-sa
    - name: models
      persistentVolumeClaim:
        claimName: spark-models-pvc
  driver:
    cores: 1
    memory: "4g"
    serviceAccount: spark
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/application_default_credentials.json
      - name: GCS_BUCKET
        value: thiagos-lake
      - name: GCS_PDF_PATH
        value: gs://juslake/thiago_x_meli.pdf
      - name: HF_HOME
        value: /opt/spark/models
      - name: TORCH_HOME
        value: /opt/spark/models/torch
      - name: DOCLING_CACHE_DIR
        value: /tmp/docling-models
    volumeMounts:
      - name: script
        mountPath: /opt/spark/scripts
      - name: gcs-adc
        mountPath: /var/secrets/google
      - name: models
        mountPath: /opt/spark/models

  executor:
    cores: 1
    instances: 2
    memory: "3g"
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/application_default_credentials.json
      - name: GCS_BUCKET
        value: thiagos-lake
      - name: HF_HOME
        value: /opt/spark/models
      - name: TORCH_HOME
        value: /opt/spark/models/torch
      - name: HF_HUB_OFFLINE
        value: "1"
    volumeMounts:
      - name: gcs-adc
        mountPath: /var/secrets/google
      - name: models
        mountPath: /opt/spark/models
