apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-multimodal-products
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: "us-central1-docker.pkg.dev/jusl-496520/my-k8s/spark-lance-gcs:4.0.2"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/scripts/job.py"
  sparkVersion: "4.0.2"
  timeToLiveSeconds: 300
  restartPolicy:
    type: Never
  sparkConf:
    "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "spark.hadoop.google.cloud.auth.type": "APPLICATION_DEFAULT"
    "spark.sql.extensions": "org.lance.spark.extensions.LanceSparkSessionExtensions"
    "spark.sql.catalog.bronze": "org.lance.spark.LanceNamespaceSparkCatalog"
    "spark.sql.catalog.bronze.impl": "dir"
    "spark.sql.catalog.bronze.root": "gs://juslake/bronze"
  volumes:
    - name: script
      configMap:
        name: spark-multimodal-products-script
    - name: models
      persistentVolumeClaim:
        claimName: spark-models-pvc
  driver:
    cores: 1
    memory: "2g"
    serviceAccount: spark
    nodeSelector:
      pool: spark
    tolerations:
      - key: pool
        operator: Equal
        value: spark
        effect: NoSchedule
    env:
      - name: GCS_BUCKET
        value: juslake
      - name: HF_HOME
        value: /opt/spark/models
      - name: TORCH_HOME
        value: /opt/spark/models/torch
      - name: HF_HUB_OFFLINE
        value: "1"
    volumeMounts:
      - name: script
        mountPath: /opt/spark/scripts
      - name: models
        mountPath: /opt/spark/models

  executor:
    cores: 1
    instances: 2
    memory: "3g"
    nodeSelector:
      pool: spark
    tolerations:
      - key: pool
        operator: Equal
        value: spark
        effect: NoSchedule
    env:
      - name: GCS_BUCKET
        value: juslake
      - name: HF_HOME
        value: /opt/spark/models
      - name: TORCH_HOME
        value: /opt/spark/models/torch
      - name: HF_HUB_OFFLINE
        value: "1"
    volumeMounts:
      - name: models
        mountPath: /opt/spark/models
