image:
  repository: ${ar_repository}/trino-lance-gcs
  tag: "476-v0.2.2"
  pullPolicy: IfNotPresent

%{ if workload_identity_sa_email != "" ~}
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: "${workload_identity_sa_email}"
%{ endif ~}

server:
  config:
    query:
      maxMemory: "256MB"

additionalCatalogs:
  bronze: |
    connector.name=lance
    lance.impl=dir
    lance.root=gs://${gcs_bucket}/bronze/
  sandbox: |
    connector.name=lance
    lance.impl=dir
    lance.root=gs://${gcs_bucket}/sandbox/

coordinator:
  additionalJVMConfig:
    - "--add-opens=java.base/java.nio=ALL-UNNAMED"
    - "--add-opens=java.base/sun.misc=ALL-UNNAMED"
  config:
    query:
      maxMemoryPerNode: "128MB"

worker:
  additionalJVMConfig:
    - "--add-opens=java.base/java.nio=ALL-UNNAMED"
    - "--add-opens=java.base/sun.misc=ALL-UNNAMED"
  config:
    query:
      maxMemoryPerNode: "128MB"
